image: golang:1.10
stages:
    - build
  
before_script:
    - go get -u github.com/jessevdk/go-flags
    - go get -u "github.com/bestmethod/go-logger"
    - go get -u "github.com/julienschmidt/httprouter"

    - cd /builds/bestmethod/go-sws
    - mkdir -p bin/linux
    - mkdir bin/windows
    - mkdir bin/osx

build:
    stage: build
    script:
        - env GOOS=linux GOARCH=amd64 go build -o bin/linux/sws
        - env GOODS=osx GOARCH=amd64 go build -o bin/osx/sws
        - env GOOS=windows GOARCH=amd64 go build -o bin/windows/sws
        - cd ..
    artifacts:
        paths:
            - bin/linux
            - bin/windows
            - bin/osx
